[features]
seeds = false
skip-lint = false

[programs.devnet]
nft_lend_borrow = "7Y6WHQ71P2qZTRobEwEyxBEbXoL6a2e45Hf6ffpf1ZXS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
